version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      # Map localhost port 8080 to docker image port 80.
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
